Repository onclick-academy/onclick, pull requests merged in 2024-05, with the labels that each got.

#11 feat[front]: Implement Courses&instractor dashboard
  package-lock.json
  package.json
  src/Img/replace.jpg
  src/Img/training-course.png
  src/app/dashboard/page.tsx
  src/app/login/page.tsx
  src/components/dashboard/Actionlist.tsx
  src/components/dashboard/Courses.tsx
  src/components/dashboard/Drawer.tsx
  src/components/dashboard/Instructors.tsx
  src/components/ui/badge.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/drawer.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/separator.tsx
  src/components/ui/table.tsx
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#19 feat/18/implement-wishlist-page
  package-lock.json
  package.json
  src/app/globals.css
  src/app/wishlist/[id]/page.tsx
  src/components/Hero/Header.tsx
  src/components/Hero/Hero.css
  src/components/Hero/Hero.tsx
  src/components/Hero/Landing.tsx
  src/components/Hero/NavMenu.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/command.tsx
  src/components/ui/sheet.tsx
  src/components/ui/tooltip.tsx
  src/constants/Btn.tsx
  yarn.lock
Labels: feature

#22 fix(front): Fix `Header`
  next.config.mjs
  public/images/hero-bg.png
  public/images/hero-img.png
  public/images/shape-1.png
  public/images/shape-2.png
  public/images/shape-3.png
  src/app/dashboard/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/wishlist/[id]/page.tsx
  src/components/Hero/Header.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/Landing.tsx
  src/components/dashboard/Actionlist.tsx
  src/components/dashboard/Courses.tsx
  src/components/dashboard/Drawer.tsx
  src/components/dashboard/Instructors.tsx
  src/components/ui/badge.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/drawer.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/table.tsx
  src/components/ui/tooltip.tsx
  src/constants/Btn.tsx
  src/styles/globals.css
  src/styles/index.css
Labels: bug
